# Generated by Django 4.2.4 on 2023-09-06 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='post_media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'mkv'])]),
        ),
    ]
